# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Play"
  lane :deployPro do
    gradle(
      task: "clean app:bundleProRelease"
    )
    upload_to_play_store(
      track: 'open_testing',
      package_name: 'at.tomtasche.reader.pro',
      skip_upload_metadata: true,
      skip_upload_changelogs: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
    gradle(task: "app:uploadCrashlyticsSymbolFileProRelease")
  end

  desc "Deploy a new version to the Google Play"
  lane :deployLite do
    gradle(
      task: "clean app:bundleLiteRelease"
    )
    upload_to_play_store(
      track: 'open_testing',
      package_name: 'at.tomtasche.reader',
      skip_upload_metadata: true,
      skip_upload_changelogs: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      version_codes_to_retain: [93]
    )
    gradle(task: "app:uploadCrashlyticsSymbolFileLiteRelease")
  end

  lane :tests do
    gradle(task: "connectedAndroidTest")
  end
end
