default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Play"
  lane :deployPro do
    gradle(
      task: "clean"
    )

    gradle(
      task: "bundle",
      flavor: "Pro",
      build_type: "Release"
    )
    upload_to_play_store(
      track: 'internal',
      package_name: 'at.tomtasche.reader.pro',
      skip_upload_metadata: true,
      skip_upload_changelogs: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
    gradle(task: "app:uploadCrashlyticsSymbolFileProRelease")
  end

  desc "Deploy a new version to the Google Play"
  lane :deployLite do
    gradle(
      task: "clean"
    )

    gradle(
      task: "bundle",
      flavor: "Lite",
      build_type: "Release"
    )
    upload_to_play_store(
      track: 'internal',
      package_name: 'at.tomtasche.reader',
      skip_upload_metadata: true,
      skip_upload_changelogs: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
    gradle(task: "app:uploadCrashlyticsSymbolFileLiteRelease")
  end

  lane :tests do
    gradle(task: "connectedAndroidTest")
  end
end
